name: Pages build and deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Correct GitHub Actions syntax

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1  # Correct GitHub Actions syntax
        with:
          ruby-version: 3.1  # Ruby version you want to use

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # This installs dependencies defined in Gemfile

      - name: Build site
        run: |
          bundle exec jekyll build  # Build the Jekyll site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  #
