name: CI/CD Workflow for Build, Report, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: actions/setup-node@v3  # Or setup any other environment (e.g., Node.js, Ruby)
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install  # Adjust if your project uses different package managers

      - name: Build site
        run: |
          npm run build  # Adjust with the correct build command

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist  # Adjust to your build directory

      - name: Post Checkout cleanup
        run: |
          git config --global --add safe.directory /home/runner/work/_temp
          git config --local --unset-all core.sshCommand

      - name: Cleaning up orphan processes
        run: |
          pkill -9 $(pgrep -f "your_process_name")  # Adjust as needed

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up job
        run: |
          echo "Setting up report build status job"

      - name: Report build status
        run: |
